# Generated by Django 6.0.1 on 2026-01-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='prescribing_facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
